export const WAITING = 'WAITING'
export const PLAYING = 'PLAYING'
export const COUNTDOWN = 'COUNTDOWN'
export const GAME_ERROR = 'GAME_ERROR'
export const JOIN_GAME = 'JOIN_GAME'
export const GAME_OVER = 'GAME_OVER'
